#%RAML 1.0
title: Test Studio
version: v1
protocols: [HTTPS]
baseUri: https://example.com/api/{version}
mediaType: application/json

types:
  uuid:
    type: string
    pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$
  testStep:
    type: string
  TestCase:
    properties:
      id: 
        type: uuid
        required: false
      testCaseName: string
      testCaseDescriptipn: string
      testSteps: testStep []
      expectedResult: string
      actualResult: string
      testType: string
      priority: string
      automation: boolean
      comments: string
      createdDate: 
        type: datetime
        required: false
      modifiedDate: 
        type: datetime
        required: false
      isActive:
        type: boolean
        required: false
  
  TestCaseMeta:
    properties:
      testCaseId: 
        type: uuid
        required: false
      companyId: uuid
      moduleId: uuid
      submoduleId: uuid

  Error:
    properties:
      message : string
  x-user-date:
    properties:
      userId: uuid


/testcase:
  /{companyId}/{moduleId}/{submoduleId}:
    get:
      description: Get all test case in a given company, module and submodule
      responses:
        200:
          headers:
            Key:
              type: x-user-date
            Cookie:
              type: string
          body:
            application/json:
              type: TestCase []
              example:
                [{"testCaseName":"","testCaseDescriptipn":"","testSteps":["Do this","Do that"],"expectedResult":"","actualResult":"","testType":"","priority":"","automation":true,"comments":""}]
        501:
          body:
            application/json:
              type: Error
              example:
                 {"message":"Internal Server Error"}
  post:
    

              


