#%RAML 1.0
title: smallretail
version: v1
protocols: [HTTPS]
baseUri: https://example.com/api/{version}
mediaType: application/json

types:
  uuid:
    type: string
    pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$
  testStep:
    type: string
  TestCase:
    properties:
      id: 
        type: uuid
        required: false
      testCaseName: string
      testCaseDescriptipn: string
      testSteps: [testStep]
      expectedResult: string
      actualResult: string
      testType: string
      priority: string
      automation: boolean
      comments: string
      createdDate: 
        type: datetime
        required: false
      modifiedDate: 
        type: datetime
        required: false
      isActive:
        type: boolean
        required: false
      projectId: uuid
  companyId: uuid
  moduleId: uuid
  submoduleId: uuid
  TestCaseMeta:
    properties:
      testCaseId: 
        type: uuid
        required: false
      companyId: companyId
      moduleId: moduleId
      submoduleId: submoduleId


/testcase:
  /{companyIdbkj}:
  get:
    description: 


