#%RAML 1.0
title: Test Studio
version: v1
protocols: [HTTPS]
baseUri: https://example.com/api/{version}
mediaType: application/json

types:
  uuid:
    type: string
    pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$
  testStep:
    type: string
  TestCase:
    properties:
      id: 
        type: uuid
        required: false
      testCaseName: string
      testCaseDescriptipn: string
      testSteps: testStep []
      expectedResult: string
      actualResult: string
      testType: string
      priority: string
      automation: boolean
      comments: string
      projectId: uuid
      createdDate: 
        type: datetime
        required: false
      modifiedDate: 
        type: datetime
        required: false
      isActive:
        type: boolean
        required: false
  TestCaseMeta:
    properties:
      testCaseId: 
        type: uuid
        required: false
      companyId: uuid
      projectId: uuid
      moduleId: uuid
      submoduleId: uuid
  Error:
    properties:
      message : string
  CreateTestCaseBO:
    properties:
      testCase : TestCase
      testCaseMeta : TestCaseMeta
  ListTestCaseBO:
    properties:
      id: uuid
      testCaseName: string

/testcase:
  post:
    headers:
        x-user-date: string
        Cookie:
          type: string
    description: Create a test case and map it to given company, project, module and sub-module
    body:
      application/json:
        type : CreateTestCaseBO
        example: {"testCase":{"testCaseName":"","testCaseDescriptipn":"","testSteps":["Do this","Do that"],"expectedResult":"","actualResult":"","testType":"","priority":"","automation":true,"comments":""},"testCaseMeta":{"companyId":"eae0cef8-caed-11e9-a32f-2a2ae2dbcce4","projectId":"eae0cef8-caed-11e9-a32f-2a2ae2dbcce4","moduleId":"eae0cef8-caed-11e9-a32f-2a2ae2dbcce4","submoduleId":"eae0cef8-caed-11e9-a32f-2a2ae2dbcce4"}}
    responses:
      201:
        body:
          application/json:
            type: TestCase
            example:
              {"testCaseId":"eae0cef8-caed-11e9-a32f-2a2ae2dbcce4","testCaseName":"","testCaseDescriptipn":"","testSteps":["Do this","Do that"],"expectedResult":"","actualResult":"","testType":"","priority":"","automation":true,"comments":"","created_date":"","modified_date":""}
      501:
          body:
            application/json:
              type: Error
              example:
                 {"message":"Internal Server Error"}
  put:
    headers:
        x-user-date: string
        Cookie:
          type: string
    description: Edit a test case
    body:
      application/json:
        type: TestCase
        example:
          {"testCaseId":"eae0cef8-caed-11e9-a32f-2a2ae2dbcce4","testCaseName":"","testCaseDescriptipn":"","testSteps":["Do this","Do that"],"expectedResult":"","actualResult":"","testType":"","priority":"","automation":true,"comments":""}
    responses:
      200:
        body:
          application/json:
            type: TestCase
            example:
              {"testCaseId":"eae0cef8-caed-11e9-a32f-2a2ae2dbcce4","testCaseName":"","testCaseDescriptipn":"","testSteps":["Do this","Do that"],"expectedResult":"","actualResult":"","testType":"","priority":"","automation":true,"comments":""}
      501:
          body:
            application/json:
              type: Error
              example:
                 {"message":"Internal Server Error"}

  /{testCaseId}:
    get:
      description: Get details of a particular test case
      headers:
        x-user-date: string
        Cookie:
          type: string
      responses:
        200:
          body:
            application/json:
              type: TestCase
              example:
                {"testCaseName":"","testCaseDescriptipn":"","testSteps":["Do this","Do that"],"expectedResult":"","actualResult":"","testType":"","priority":"","automation":true,"comments":""}
        204:
          body: nil
        501:
          body:
            application/json:
              type: Error
              example:
                 {"message":"Internal Server Error"}
    delete:
      description: Deletes a test case
      headers:
        x-user-date: string
        Cookie:
          type: string
      responses:
        204:
          body: nil
        501:
          body:
            application/json:
              type: Error
              example:
                 {"message":"Internal Server Error"}

  /{companyId}/{projectId}/{moduleId}/{submoduleId}:
    get:
      description: Get all test case in a given company, project, module and submodule
      headers:
            x-user-date: string
            Cookie:
              type: string
      responses:
        200:
          body:
            application/json:
              type: ListTestCaseBO []
              example:
                [{"id": "eae0cef8-caed-11e9-a32f-2a2ae2dbcce5", "testCaseName":""}]
        501:
          body:
            application/json:
              type: Error
              example:
                 {"message":"Internal Server Error"}
  

    
              
      
            

              


